---
- hosts: cache_instances
  become: yes
  become_user: cachesys

  vars:
    temp_folder: /tmp/
    source_license: /opt/installers/
    instance_control_cmd: cache
    instance_session_cmd: csession
    instance_owner: cachesys
    license_key_filename: cache.key

  roles:
  - deploy
