---
- hosts: iris_instances
  become: yes
  become_user: irisowner

  vars:
    temp_folder: /tmp/
    source_license: /opt/installers/
    instance_control_cmd: iris
    instance_session_cmd: irissession
    instance_owner: irissys
    license_key_filename: iris.key

  roles:
  - deploy
